-- ============================================================================
-- DS1: Hotel Accommodation Management System
-- Data Model Definition
-- ============================================================================

-- Hotels table
CREATE TABLE IF NOT EXISTS TOURISM_ADMIN.HOTELS_DS1 (
  HOTEL_ID NUMBER PRIMARY KEY,
  HOTEL_NAME VARCHAR2(100) NOT NULL,
  CITY VARCHAR2(100),
  COUNTRY VARCHAR2(100),
  STAR_RATING NUMBER(1),
  ROOMS_TOTAL NUMBER,
  PRICE_PER_NIGHT NUMBER(8,2),
  POOL CHAR(1),
  WIFI CHAR(1),
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE
) TABLESPACE USERS;

-- Room types
CREATE TABLE IF NOT EXISTS TOURISM_ADMIN.ROOM_TYPES_DS1 (
  ROOM_TYPE_ID NUMBER PRIMARY KEY,
  HOTEL_ID NUMBER REFERENCES TOURISM_ADMIN.HOTELS_DS1(HOTEL_ID),
  ROOM_TYPE_NAME VARCHAR2(50),
  CAPACITY NUMBER,
  BASE_PRICE NUMBER(8,2),
  TAX_RATE NUMBER(3,2),
  AVAILABILITY CHAR(1)
) TABLESPACE USERS;

-- Bookings
CREATE TABLE IF NOT EXISTS TOURISM_ADMIN.BOOKINGS_DS1 (
  BOOKING_ID NUMBER PRIMARY KEY,
  HOTEL_ID NUMBER REFERENCES TOURISM_ADMIN.HOTELS_DS1(HOTEL_ID),
  GUEST_NAME VARCHAR2(100),
  CHECK_IN_DATE DATE,
  CHECK_OUT_DATE DATE,
  TOTAL_AMOUNT NUMBER(10,2),
  CURRENCY VARCHAR2(3),
  CREATED_DATE TIMESTAMP DEFAULT SYSDATE
) TABLESPACE USERS;

-- Indexes for performance
CREATE INDEX IDX_HOTELS_CITY ON TOURISM_ADMIN.HOTELS_DS1(CITY);
CREATE INDEX IDX_HOTELS_RATING ON TOURISM_ADMIN.HOTELS_DS1(STAR_RATING);
CREATE INDEX IDX_BOOKINGS_HOTEL ON TOURISM_ADMIN.BOOKINGS_DS1(HOTEL_ID);
CREATE INDEX IDX_BOOKINGS_DATE ON TOURISM_ADMIN.BOOKINGS_DS1(CHECK_IN_DATE);

-- Sample data from OpenStreetMap POI
BEGIN
  DELETE FROM TOURISM_ADMIN.HOTELS_DS1;
  
  INSERT INTO TOURISM_ADMIN.HOTELS_DS1 VALUES 
    (1, 'InterContinental Bucharest', 'Bucharest', 'Romania', 5, 92, 185.00, 'Y', 'Y', SYSDATE);
  INSERT INTO TOURISM_ADMIN.HOTELS_DS1 VALUES 
    (2, 'Radisson Blu Hotel Bucharest', 'Bucharest', 'Romania', 4, 75, 145.00, 'Y', 'Y', SYSDATE);
  INSERT INTO TOURISM_ADMIN.HOTELS_DS1 VALUES 
    (3, 'Hotel Tâmpa', 'Brașov', 'Romania', 3, 48, 95.00, 'N', 'Y', SYSDATE);
  
  COMMIT;
END;
/

PROMPT DS_1 Hotel tables created and populated
