### REST Data HTTP service
server.port=8097
server.servlet.context-path=/DSA-DOC-CSVService/rest

### logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Exclude DataSource auto-configuration (no database needed)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# SpringBoot Security
spring.security.user.name=developer
spring.security.user.password=iis
