BEGIN
  EXECUTE IMMEDIATE 'DROP USER TOURISM_ADMIN CASCADE';
  DBMS_OUTPUT.PUT_LINE('Old user dropped');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('No old user');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER TOURISM_ADMIN IDENTIFIED BY Tourism2025';
  DBMS_OUTPUT.PUT_LINE('User created');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO TOURISM_ADMIN';
  DBMS_OUTPUT.PUT_LINE('Privileges granted');
END;
/

COMMIT;

SET PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF;
SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';

EXIT;
