ALTER SESSION SET CONTAINER=FREEPDB1;

-- Insert data into REGIONS
INSERT INTO TOURISM_ADMIN.REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP) 
VALUES (1, 'Transylvania', 'TRANS', 2500000, 45000000000);

INSERT INTO TOURISM_ADMIN.REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP) 
VALUES (2, 'Bukovina', 'BUK', 1000000, 15000000000);

INSERT INTO TOURISM_ADMIN.REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP) 
VALUES (3, 'Dobruja', 'DOB', 800000, 12000000000);

-- Insert data into DESTINATIONS  
INSERT INTO TOURISM_ADMIN.DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL) 
VALUES (1, 1, 'Brașov', 'Mountain City', 45.6408, 24.5666, 250000);

INSERT INTO TOURISM_ADMIN.DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL) 
VALUES (2, 1, 'Bran Castle', 'Historical Site', 45.5096, 25.3858, 400000);

INSERT INTO TOURISM_ADMIN.DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL) 
VALUES (3, 2, 'Suceava', 'Medieval Town', 47.6500, 26.2600, 150000);

-- Insert data into HOTELS
INSERT INTO TOURISM_ADMIN.HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT) 
VALUES (1, 1, 'Postillion Brașov', 4, 85, 10, 150.00);

INSERT INTO TOURISM_ADMIN.HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT) 
VALUES (2, 1, 'Spa Hotel Wellness', 5, 120, 5, 280.00);

INSERT INTO TOURISM_ADMIN.HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT) 
VALUES (3, 2, 'Castel Hotel Bran', 4, 45, 8, 180.00);

-- Insert data into FLIGHTS
INSERT INTO TOURISM_ADMIN.FLIGHTS (FLIGHT_ID, AIRLINE_CODE, FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, AIRCRAFT_TYPE, PASSENGERS_COUNT) 
VALUES (1, 'RO', 'RO1234', 'BUH', 'PRG', TO_TIMESTAMP('2026-04-06 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-04-06 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'Boeing 737', 180);

INSERT INTO TOURISM_ADMIN.FLIGHTS (FLIGHT_ID, AIRLINE_CODE, FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, AIRCRAFT_TYPE, PASSENGERS_COUNT) 
VALUES (2, 'RO', 'RO5678', 'OTP', 'VIE', TO_TIMESTAMP('2026-04-06 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-04-06 13:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'Airbus A320', 165);

COMMIT;

PROMPT Data inserted successfully!

-- Verify
PROMPT
PROMPT ===== DATA VERIFICATION =====
PROMPT
PROMPT Regions:
SELECT * FROM TOURISM_ADMIN.REGIONS;

PROMPT
PROMPT Destinations:
SELECT * FROM TOURISM_ADMIN.DESTINATIONS;

PROMPT
PROMPT Hotels:
SELECT * FROM TOURISM_ADMIN.HOTELS;

PROMPT
PROMPT Flights:
SELECT * FROM TOURISM_ADMIN.FLIGHTS;

EXIT;
