-- Quick Verification Test
SET PAGESIZE 0 FEEDBACK OFF
SELECT 'BOOKINGS=' || COUNT(*) FROM TOURISM_ADMIN.FACT_BOOKINGS;
SELECT 'DIM_DATE=' || COUNT(*) FROM TOURISM_ADMIN.DIM_DATE;
SELECT 'HOTELS_DS1=' || COUNT(*) FROM TOURISM_ADMIN.HOTELS_DS1;
SELECT 'FLIGHTS_DS2=' || COUNT(*) FROM TOURISM_ADMIN.FLIGHTS_DS2_CACHE;
SELECT 'CURRENCIES_DS3=' || COUNT(*) FROM TOURISM_ADMIN.CURRENCY_DS3;
SELECT 'OLAP_VIEWS=' || COUNT(*) FROM user_views WHERE view_name LIKE 'V_ANALYTICS%';
EXIT;
