-- Switch to PDB
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Check current container
PROMPT Current session container:
SHOW CON_NAME

PROMPT 

-- Create user if not exists
DECLARE
  v_user_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_user_count FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';
  IF v_user_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER TOURISM_ADMIN CASCADE';
    DBMS_OUTPUT.PUT_LINE('Dropped old TOURISM_ADMIN');
  END IF;
  
  EXECUTE IMMEDIATE 'CREATE USER TOURISM_ADMIN IDENTIFIED BY Tourism2025';
  DBMS_OUTPUT.PUT_LINE('Created TOURISM_ADMIN');
  
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO TOURISM_ADMIN';
  DBMS_OUTPUT.PUT_LINE('Granted privileges');
  
  COMMIT;
END;
/

-- Verify
PROMPT

PROMPT User verification (should show TOURISM_ADMIN):
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';

EXIT;
