-- Simple setup to create TOURISM_ADMIN user
SET ECHO OFF FEEDBACK OFF HEADING OFF VERIFY OFF PAGESIZE 0

-- Drop user if exists
BEGIN
  BEGIN
    EXECUTE IMMEDIATE 'DROP USER TOURISM_ADMIN CASCADE';
    DBMS_OUTPUT.PUT_LINE('Dropped existing TOURISM_ADMIN');
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

-- Create TOURISM_ADMIN user  
CREATE USER TOURISM_ADMIN IDENTIFIED BY Tourism2025;

-- Grant privileges
GRANT CONNECT, RESOURCE, DBA TO TOURISM_ADMIN;
GRANT UNLIMITED TABLESPACE TO TOURISM_ADMIN;
GRANT CREATE SESSION TO TOURISM_ADMIN;
GRANT CREATE TABLE TO TOURISM_ADMIN;
GRANT CREATE VIEW TO TOURISM_ADMIN;
GRANT CREATE PROCEDURE TO TOURISM_ADMIN;
GRANT CREATE SEQUENCE TO TOURISM_ADMIN;

-- Commit
COMMIT;

-- Verify
SELECT * FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';

EXIT;
