-- Simple user creation for PDB
CREATE USER TOURISM_ADMIN IDENTIFIED BY Tourism2025;
GRANT CREATE SESSION TO TOURISM_ADMIN;
GRANT UNLIMITED TABLESPACE TO TOURISM_ADMIN;
GRANT CREATE TABLE TO TOURISM_ADMIN;
GRANT CREATE VIEW TO TOURISM_ADMIN;
GRANT CREATE PROCEDURE TO TOURISM_ADMIN;
GRANT CREATE SEQUENCE TO TOURISM_ADMIN;
COMMIT;

-- Verify
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';
EXIT;
