-- Create TOURISM_ADMIN user for multitenant database
DECLARE
  v_count NUMBER;
BEGIN
  -- Check if user exists  
  SELECT COUNT(*) INTO v_count FROM DBA_USERS WHERE USERNAME IN ('C##TOURISM_ADMIN', 'TOURISM_ADMIN');
  
  DBMS_OUTPUT.PUT_LINE('Checking for existing users: ' || v_count);
  
  IF v_count > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER C##TOURISM_ADMIN CASCADE';
      DBMS_OUTPUT.PUT_LINE('Dropped C##TOURISM_ADMIN');
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('No C##TOURISM_ADMIN to drop');
    END;
    
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER TOURISM_ADMIN CASCADE';
      DBMS_OUTPUT.PUT_LINE('Dropped TOURISM_ADMIN');
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('No TOURISM_ADMIN to drop');
    END;
  END IF;
  
  -- Create new local user (for PDB)
  EXECUTE IMMEDIATE 'CREATE USER TOURISM_ADMIN IDENTIFIED BY Tourism2025';
  DBMS_OUTPUT.PUT_LINE('Created TOURISM_ADMIN');
  
  -- Grant privileges
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT RESOURCE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_OUTPUT TO TOURISM_ADMIN';
  EXECUTE IMMEDIATE 'GRANT EXECUTE ON DBMS_UTILITY TO TOURISM_ADMIN';
  DBMS_OUTPUT.PUT_LINE('Granted privileges');
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('COMMIT successful');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || ' - ' || SQLERRM);
    ROLLBACK;
    RAISE;
END;
/

-- Verify user creation
PROMPT
PROMPT ============================================
PROMPT User Verification:
PROMPT ============================================
SELECT USERNAME, ACCOUNT_STATUS, CREATED FROM DBA_USERS WHERE USERNAME = 'TOURISM_ADMIN';

EXIT;
