ALTER SESSION SET CONTAINER=FREEPDB1;

PROMPT
PROMPT ===== TOURISM ANALYTICS PLATFORM - DEPLOYMENT STATISTICS =====
PROMPT

PROMPT Tables Created:
SELECT COUNT(*) AS TABLE_COUNT FROM DBA_TABLES WHERE OWNER = 'TOURISM_ADMIN';

PROMPT
PROMPT Views Created:
SELECT COUNT(*) AS VIEW_COUNT FROM DBA_VIEWS WHERE OWNER = 'TOURISM_ADMIN';

PROMPT  
PROMPT Sequences Created:
SELECT COUNT(*) AS SEQUENCE_COUNT FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER = 'TOURISM_ADMIN';

PROMPT
PROMPT Data in REGIONS table:
SELECT COUNT(*) AS REGION_COUNT FROM TOURISM_ADMIN.REGIONS;

PROMPT
PROMPT Data in HOTELS table:
SELECT COUNT(*) AS HOTEL_COUNT FROM TOURISM_ADMIN.HOTELS;

PROMPT
PROMPT Data in FLIGHTStable:
SELECT COUNT(*) AS FLIGHT_COUNT FROM TOURISM_ADMIN.FLIGHTS;

PROMPT
PROMPT Sample Data from DESTINATIONS:
SELECT DESTINATION_ID, NAME, TYPE FROM TOURISM_ADMIN.DESTINATIONS;

PROMPT
PROMPT ===== DEPLOYMENT SUCCESSFUL =====
PROMPT

EXIT;
