### REST Data HTTP service
server.port=8093
server.servlet.context-path=/DSA-NoSQL-MongoDBService/rest

### MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/tourism_data

### logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Exclude DataSource and Security auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# SpringBoot Security
spring.security.user.name=developer
spring.security.user.password=iis
