-- ============================================================================
-- TEMA L3: ANALYTICAL INTEGRATION MODEL - OLAP IMPLEMENTATION
-- Consolidation Layer + ROLAP Dimensional Schema + Analytical Views
-- ============================================================================

ALTER SESSION SET CONTAINER=FREEPDB1;

PROMPT ========================================================================
PROMPT TEMA L3: Building Analytical Integration Model (OLAP)
PROMPT ========================================================================

-- ============================================================================
-- LEVEL 1: DATA CONSOLIDATION VIEWS (Joining Multi-Source Federation)
-- ============================================================================

PROMPT [1] Creating Data Consolidation Views (Multi-Source Joins)...

-- Consolidation View 1: Booking with Guest and Hotel Information
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_CONSOLIDATE_BOOKINGS AS
SELECT 
  b.BOOKING_ID,
  b.GUEST_NAME,
  h.HOTEL_ID,
  h.HOTEL_NAME,
  h.CITY,
  h.COUNTRY,
  h.STAR_RATING,
  b.CHECK_IN_DATE,
  b.CHECK_OUT_DATE,
  b.NIGHTS,
  r.ROOM_TYPE,
  r.CAPACITY,
  r.NIGHTLY_RATE,
  r.CURRENCY,
  b.TOTAL_PRICE,
  b.BOOKING_STATUS,
  'BOOKING_MASTER' as RECORD_TYPE
FROM 
  TOURISM_ADMIN.V_DS1_BOOKINGS b
  INNER JOIN TOURISM_ADMIN.V_DS1_HOTELS h ON b.HOTEL_ID = h.HOTEL_ID
  LEFT JOIN TOURISM_ADMIN.V_DS1_ROOMS r ON b.ROOM_TYPE = r.ROOM_TYPE AND h.HOTEL_ID = r.HOTEL_ID;

-- Consolidation View 2: Accommodation Inventory with Multi-Currency Support
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_CONSOLIDATE_ACCOMMODATION AS
SELECT 
  h.HOTEL_ID,
  h.HOTEL_NAME,
  h.CITY,
  h.COUNTRY,
  h.STAR_RATING,
  h.TOTAL_ROOMS,
  h.YEAR_OPENED,
  r.ROOM_TYPE_ID,
  r.ROOM_TYPE,
  r.CAPACITY,
  r.NIGHTLY_RATE,
  r.CURRENCY,
  c.EUR_RATE,
  ROUND(r.NIGHTLY_RATE / NULLIF(c.EUR_RATE, 0), 2) as NIGHTLY_RATE_EUR,
  r.AVAILABLE_ROOMS
FROM 
  TOURISM_ADMIN.V_DS1_HOTELS h
  INNER JOIN TOURISM_ADMIN.V_DS1_ROOMS r ON h.HOTEL_ID = r.HOTEL_ID
  LEFT JOIN TOURISM_ADMIN.V_DS3_CURRENCIES c ON r.CURRENCY = c.CURRENCY_CODE
WHERE 
  c.CURRENCY_CODE IS NOT NULL;

-- Consolidation View 3: Travel Integration (Bookings + Flights)
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_CONSOLIDATE_TRAVEL AS
SELECT 
  b.BOOKING_ID,
  b.GUEST_NAME,
  h.HOTEL_NAME,
  h.CITY,
  b.CHECK_IN_DATE,
  b.CHECK_OUT_DATE,
  b.NIGHTS,
  f.CALLSIGN,
  f.ORIGIN_AIRPORT,
  f.DESTINATION_AIRPORT,
  f.ORIGIN_COUNTRY,
  f.ALTITUDE_M,
  b.TOTAL_PRICE,
  b.BOOKING_STATUS
FROM 
  TOURISM_ADMIN.V_DS1_BOOKINGS b
  INNER JOIN TOURISM_ADMIN.V_DS1_HOTELS h ON b.HOTEL_ID = h.HOTEL_ID
  CROSS JOIN TOURISM_ADMIN.V_DS2_FLIGHTS f;

COMMIT;
PROMPT Consolidation views created

-- ============================================================================
-- LEVEL 2: ROLAP DIMENSIONAL TABLES
-- ============================================================================

PROMPT [2] Creating ROLAP Dimensional Tables...

-- Dimension Table 1: TIME DIMENSION
CREATE TABLE TOURISM_ADMIN.DIM_DATE (
  DATE_ID NUMBER PRIMARY KEY,
  FULL_DATE DATE NOT NULL,
  YEAR NUMBER(4),
  QUARTER NUMBER(1),
  MONTH NUMBER(2),
  MONTH_NAME VARCHAR2(20),
  DAY_OF_MONTH NUMBER(2),
  DAY_NAME VARCHAR2(20),
  WEEK_OF_YEAR NUMBER(2),
  IS_WEEKEND CHAR(1),
  IS_HOLIDAY CHAR(1)
) TABLESPACE USERS;

-- Dimension Table 2: LOCATION DIMENSION
CREATE TABLE TOURISM_ADMIN.DIM_LOCATION (
  LOCATION_ID NUMBER PRIMARY KEY,
  COUNTRY VARCHAR2(50),
  CITY VARCHAR2(100),
  REGION VARCHAR2(100),
  LATITUDE NUMBER(10,6),
  LONGITUDE NUMBER(11,6)
) TABLESPACE USERS;

-- Dimension Table 3: ACCOMMODATION DIMENSION
CREATE TABLE TOURISM_ADMIN.DIM_ACCOMMODATION (
  ACCOMMODATION_ID NUMBER PRIMARY KEY,
  HOTEL_ID NUMBER,
  HOTEL_NAME VARCHAR2(200),
  STAR_RATING NUMBER(2,1),
  TOTAL_ROOMS NUMBER,
  YEAR_OPENED NUMBER(4),
  ROOM_TYPE VARCHAR2(50),
  CAPACITY NUMBER,
  CURRENCY VARCHAR2(3)
) TABLESPACE USERS;

-- Dimension Table 4: CURRENCY DIMENSION
CREATE TABLE TOURISM_ADMIN.DIM_CURRENCY (
  CURRENCY_ID NUMBER PRIMARY KEY,
  CURRENCY_CODE VARCHAR2(3),
  CURRENCY_NAME VARCHAR2(50),
  EUR_RATE NUMBER(12,6),
  REGION_ASSOCIATED VARCHAR2(50)
) TABLESPACE USERS;

-- Dimension Table 5: TRANSPORT DIMENSION
CREATE TABLE TOURISM_ADMIN.DIM_TRANSPORT (
  TRANSPORT_ID NUMBER PRIMARY KEY,
  TRANSPORT_TYPE VARCHAR2(20),
  CALLSIGN VARCHAR2(20),
  ORIGIN_COUNTRY VARCHAR2(50),
  DESTINATION_COUNTRY VARCHAR2(50),
  ORIGIN_AIRPORT VARCHAR2(10),
  DESTINATION_AIRPORT VARCHAR2(10),
  ALTITUDE_CATEGORY VARCHAR2(20)
) TABLESPACE USERS;

-- Populate Dimension Tables
PROMPT Loading dimension data...

BEGIN
  -- DIM_DATE: Create entries for Apr 6-12, 2026
  DELETE FROM TOURISM_ADMIN.DIM_DATE;
  FOR i IN 1..7 LOOP
    INSERT INTO TOURISM_ADMIN.DIM_DATE (
      DATE_ID, FULL_DATE, YEAR, QUARTER, MONTH, MONTH_NAME, 
      DAY_OF_MONTH, DAY_NAME, WEEK_OF_YEAR, IS_WEEKEND, IS_HOLIDAY
    ) VALUES (
      20260400 + i,
      TO_DATE('2026-04-' || LPAD(5+i, 2, '0'), 'YYYY-MM-DD'),
      2026,
      2,
      4,
      'April',
      5+i,
      TO_CHAR(TO_DATE('2026-04-' || LPAD(5+i, 2, '0'), 'YYYY-MM-DD'), 'Day'),
      15,
      CASE WHEN TO_CHAR(TO_DATE('2026-04-' || LPAD(5+i, 2, '0'), 'YYYY-MM-DD'), 'D') IN ('1', '7') THEN 'Y' ELSE 'N' END,
      'N'
    );
  END LOOP;
  COMMIT;
  
  -- DIM_LOCATION
  DELETE FROM TOURISM_ADMIN.DIM_LOCATION;
  INSERT INTO TOURISM_ADMIN.DIM_LOCATION VALUES (1, 'Romania', 'Bucharest', 'Wallachia', 44.4268, 26.1025);
  INSERT INTO TOURISM_ADMIN.DIM_LOCATION VALUES (2, 'Romania', 'Brașov', 'Transylvania', 45.6500, 24.5833);
  INSERT INTO TOURISM_ADMIN.DIM_LOCATION VALUES (3, 'Austria', 'Vienna', 'Northeastern Austria', 48.2066, 16.3738);
  INSERT INTO TOURISM_ADMIN.DIM_LOCATION VALUES (4, 'Germany', 'Frankfurt', 'Hesse', 50.1109, 8.6821);
  INSERT INTO TOURISM_ADMIN.DIM_LOCATION VALUES (5, 'Czech Republic', 'Prague', 'Bohemia', 50.0755, 14.4378);
  COMMIT;
  
  -- DIM_ACCOMMODATION
  DELETE FROM TOURISM_ADMIN.DIM_ACCOMMODATION;
  INSERT INTO TOURISM_ADMIN.DIM_ACCOMMODATION VALUES (1, 101, 'Intercontinental Bucharest', 5, 250, 1979, 'Deluxe Suite', 2, 'USD');
  INSERT INTO TOURISM_ADMIN.DIM_ACCOMMODATION VALUES (2, 101, 'Intercontinental Bucharest', 5, 250, 1979, 'Standard Room', 2, 'USD');
  INSERT INTO TOURISM_ADMIN.DIM_ACCOMMODATION VALUES (3, 102, 'Radisson Blu Brașov', 4, 180, 2009, 'Executive Suite', 2, 'EUR');
  INSERT INTO TOURISM_ADMIN.DIM_ACCOMMODATION VALUES (4, 102, 'Radisson Blu Brașov', 4, 180, 2009, 'Standard Room', 2, 'EUR');
  INSERT INTO TOURISM_ADMIN.DIM_ACCOMMODATION VALUES (5, 103, 'Hotel Tâmpa', 3, 45, 1995, 'Standard Room', 2, 'EUR');
  COMMIT;
  
  -- DIM_CURRENCY
  DELETE FROM TOURISM_ADMIN.DIM_CURRENCY;
  INSERT INTO TOURISM_ADMIN.DIM_CURRENCY VALUES (1, 'EUR', 'Euro', 1.000000, 'Europe');
  INSERT INTO TOURISM_ADMIN.DIM_CURRENCY VALUES (2, 'USD', 'US Dollar', 1.087000, 'North America');
  INSERT INTO TOURISM_ADMIN.DIM_CURRENCY VALUES (3, 'GBP', 'British Pound', 0.856000, 'United Kingdom');
  INSERT INTO TOURISM_ADMIN.DIM_CURRENCY VALUES (4, 'CHF', 'Swiss Franc', 0.967000, 'Switzerland');
  INSERT INTO TOURISM_ADMIN.DIM_CURRENCY VALUES (5, 'RON', 'Romanian Leu', 4.972000, 'Romania');
  COMMIT;
  
  -- DIM_TRANSPORT
  DELETE FROM TOURISM_ADMIN.DIM_TRANSPORT;
  INSERT INTO TOURISM_ADMIN.DIM_TRANSPORT VALUES (1, 'AIR', 'RO1001', 'Romania', 'Austria', 'OTP', 'VIE', 'HIGH');
  INSERT INTO TOURISM_ADMIN.DIM_TRANSPORT VALUES (2, 'AIR', 'RO1002', 'Romania', 'Czech Republic', 'BUH', 'PRG', 'HIGH');
  INSERT INTO TOURISM_ADMIN.DIM_TRANSPORT VALUES (3, 'AIR', 'LH501', 'Germany', 'Romania', 'VIE', 'BUH', 'HIGH');
  COMMIT;
  
END;
/

PROMPT Dimension tables loaded

-- ============================================================================
-- LEVEL 3: ROLAP FACT TABLES
-- ============================================================================

PROMPT [3] Creating ROLAP Fact Tables...

-- Fact Table 1: BOOKING_FACTS
CREATE TABLE TOURISM_ADMIN.FACT_BOOKINGS (
  BOOKING_FACT_ID VARCHAR2(50) PRIMARY KEY,
  BOOKING_ID VARCHAR2(20),
  ACCOMMODATION_ID NUMBER,
  LOCATION_ID NUMBER,
  CHECK_IN_DATE_ID NUMBER,
  CHECK_OUT_DATE_ID NUMBER,
  NIGHTS_COUNT NUMBER,
  ROOM_RATE DECIMAL(10,2),
  CURRENCY_ID NUMBER,
  TOTAL_AMOUNT_LOCAL DECIMAL(12,2),
  TOTAL_AMOUNT_EUR DECIMAL(12,2),
  BOOKING_STATUS VARCHAR2(20),
  GUEST_NAME VARCHAR2(100)
) TABLESPACE USERS;

-- Fact Table 2: ACCOMMODATION_FACTS
CREATE TABLE TOURISM_ADMIN.FACT_ACCOMMODATION (
  ACCOMMODATION_FACT_ID VARCHAR2(50) PRIMARY KEY,
  ACCOMMODATION_ID NUMBER,
  LOCATION_ID NUMBER,
  DATE_ID NUMBER,
  AVAILABLE_ROOMS NUMBER,
  OCCUPANCY_RATE DECIMAL(5,2),
  REVENUE_POTENTIAL DECIMAL(12,2),
  CURRENCY_ID NUMBER
) TABLESPACE USERS;

-- Populate Fact Tables
PROMPT Loading fact table data...

BEGIN
  -- FACT_BOOKINGS
  DELETE FROM TOURISM_ADMIN.FACT_BOOKINGS;
  INSERT INTO TOURISM_ADMIN.FACT_BOOKINGS (
    BOOKING_FACT_ID, BOOKING_ID, ACCOMMODATION_ID, LOCATION_ID, 
    CHECK_IN_DATE_ID, CHECK_OUT_DATE_ID, NIGHTS_COUNT, ROOM_RATE, 
    CURRENCY_ID, TOTAL_AMOUNT_LOCAL, BOOKING_STATUS, GUEST_NAME
  ) VALUES (
    'BK_FACT_001', 'BK001', 1, 1, 20260410, 20260412, 2, 380.00, 2, 760.00, 'CONFIRMED', 'John Smith'
  );
  INSERT INTO TOURISM_ADMIN.FACT_BOOKINGS (
    BOOKING_FACT_ID, BOOKING_ID, ACCOMMODATION_ID, LOCATION_ID, 
    CHECK_IN_DATE_ID, CHECK_OUT_DATE_ID, NIGHTS_COUNT, ROOM_RATE, 
    CURRENCY_ID, TOTAL_AMOUNT_LOCAL, BOOKING_STATUS, GUEST_NAME
  ) VALUES (
    'BK_FACT_002', 'BK002', 3, 2, 20260408, 20260410, 2, 300.00, 1, 600.00, 'CONFIRMED', 'Maria Garcia'
  );
  COMMIT;
  
  -- FACT_ACCOMMODATION
  DELETE FROM TOURISM_ADMIN.FACT_ACCOMMODATION;
  INSERT INTO TOURISM_ADMIN.FACT_ACCOMMODATION (
    ACCOMMODATION_FACT_ID, ACCOMMODATION_ID, LOCATION_ID, DATE_ID,
    AVAILABLE_ROOMS, OCCUPANCY_RATE, REVENUE_POTENTIAL, CURRENCY_ID
  ) VALUES (
    'ACC_FACT_001', 1, 1, 20260410, 15, 20.00, 5700.00, 2
  );
  INSERT INTO TOURISM_ADMIN.FACT_ACCOMMODATION (
    ACCOMMODATION_FACT_ID, ACCOMMODATION_ID, LOCATION_ID, DATE_ID,
    AVAILABLE_ROOMS, OCCUPANCY_RATE, REVENUE_POTENTIAL, CURRENCY_ID
  ) VALUES (
    'ACC_FACT_002', 3, 2, 20260410, 8, 50.00, 2400.00, 1
  );
  COMMIT;
  
END;
/

PROMPT Fact tables loaded

-- ============================================================================
-- LEVEL 4: OLAP ANALYTICAL VIEWS
-- ============================================================================

PROMPT [4] Creating OLAP Analytical Views...

-- OLAP View 1: Booking Revenue Analysis by Hotel (ROLLUP)
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_REVENUE_ROLLUP AS
SELECT 
  GROUPING_ID(d.HOTEL_NAME, d.STAR_RATING, d.ROOM_TYPE) as GROUPING_LEVEL,
  CASE 
    WHEN GROUPING(d.HOTEL_NAME) = 1 THEN 'ALL_HOTELS'
    ELSE d.HOTEL_NAME
  END as HOTEL_NAME,
  CASE 
    WHEN GROUPING(d.STAR_RATING) = 1 THEN NULL
    ELSE d.STAR_RATING
  END as STAR_RATING,
  CASE 
    WHEN GROUPING(d.ROOM_TYPE) = 1 THEN 'ALL_ROOMS'
    ELSE d.ROOM_TYPE
  END as ROOM_TYPE,
  COUNT(*) as BOOKING_COUNT,
  SUM(fb.TOTAL_AMOUNT_LOCAL) as TOTAL_REVENUE_LOCAL,
  SUM(fb.TOTAL_AMOUNT_EUR) as TOTAL_REVENUE_EUR,
  ROUND(AVG(fb.TOTAL_AMOUNT_EUR), 2) as AVG_BOOKING_VALUE_EUR,
  SUM(fb.NIGHTS_COUNT) as TOTAL_NIGHTS
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
GROUP BY ROLLUP (d.HOTEL_NAME, d.STAR_RATING, d.ROOM_TYPE);

-- OLAP View 2: Revenue Analysis by Location and Currency (CUBE)
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_LOCATION_CUBE AS
SELECT 
  GROUPING_ID(c.COUNTRY, c.CITY, cur.CURRENCY_CODE) as GROUPING_LEVEL,
  CASE 
    WHEN GROUPING(c.COUNTRY) = 1 THEN 'TOTAL'
    ELSE c.COUNTRY
  END as COUNTRY,
  CASE 
    WHEN GROUPING(c.CITY) = 1 THEN 'ALL_CITIES'
    ELSE c.CITY
  END as CITY,
  CASE 
    WHEN GROUPING(cur.CURRENCY_CODE) = 1 THEN 'MULTI_CURRENCY'
    ELSE cur.CURRENCY_CODE
  END as CURRENCY_CODE,
  COUNT(DISTINCT fb.BOOKING_ID) as BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_LOCAL) as REVENUE_LOCAL,
  SUM(fb.TOTAL_AMOUNT_EUR) as REVENUE_EUR,
  ROUND(SUM(fb.TOTAL_AMOUNT_EUR) / NULLIF(COUNT(DISTINCT fb.BOOKING_ID), 0), 2) as AVG_VALUE_EUR,
  SUM(CASE WHEN fb.BOOKING_STATUS = 'CONFIRMED' THEN 1 ELSE 0 END) as CONFIRMED_BOOKINGS
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_LOCATION c ON fb.LOCATION_ID = c.LOCATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_CURRENCY cur ON fb.CURRENCY_ID = cur.CURRENCY_ID
GROUP BY CUBE (c.COUNTRY, c.CITY, cur.CURRENCY_CODE);

-- OLAP View 3: Temporal Analysis with Window Functions
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_TEMPORAL_TREND AS
SELECT 
  d.FULL_DATE,
  d.MONTH_NAME,
  d.WEEK_OF_YEAR,
  COUNT(*) OVER (ORDER BY d.FULL_DATE) as CUMULATIVE_BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_EUR) OVER (ORDER BY d.FULL_DATE) as CUMULATIVE_REVENUE_EUR,
  SUM(fb.TOTAL_AMOUNT_EUR) OVER (PARTITION BY d.MONTH ORDER BY d.FULL_DATE) as MONTHLY_RUNNING_TOTAL,
  ROW_NUMBER() OVER (ORDER BY fb.TOTAL_AMOUNT_EUR DESC) as REVENUE_RANK,
  DENSE_RANK() OVER (PARTITION BY d.MONTH ORDER BY fb.TOTAL_AMOUNT_EUR DESC) as MONTHLY_RANK,
  FIRST_VALUE(fb.TOTAL_AMOUNT_EUR) OVER (PARTITION BY d.MONTH ORDER BY d.FULL_DATE) as FIRST_BOOKING_VALUE_MONTH,
  LAST_VALUE(fb.TOTAL_AMOUNT_EUR) OVER (PARTITION BY d.MONTH ORDER BY d.FULL_DATE 
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as LAST_BOOKING_VALUE_MONTH
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_DATE d ON fb.CHECK_IN_DATE_ID = d.DATE_ID
ORDER BY 
  d.FULL_DATE;

-- OLAP View 4: Occupancy Rate Analysis
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_OCCUPANCY AS
SELECT 
  d.HOTEL_NAME,
  d.STAR_RATING,
  dd.FULL_DATE,
  fa.AVAILABLE_ROOMS,
  fa.OCCUPANCY_RATE,
  AVG(fa.OCCUPANCY_RATE) OVER (PARTITION BY d.HOTEL_NAME ORDER BY dd.FULL_DATE 
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) as MOVING_AVG_OCCUPANCY_3DAY,
  LEAD(fa.OCCUPANCY_RATE) OVER (PARTITION BY d.HOTEL_NAME ORDER BY dd.FULL_DATE) as NEXT_DAY_OCCUPANCY,
  LAG(fa.OCCUPANCY_RATE) OVER (PARTITION BY d.HOTEL_NAME ORDER BY dd.FULL_DATE) as PREV_DAY_OCCUPANCY,
  MAX(fa.OCCUPANCY_RATE) OVER (PARTITION BY d.HOTEL_NAME) as MAX_OCCUPANCY,
  SUM(fa.REVENUE_POTENTIAL) OVER (PARTITION BY d.HOTEL_NAME) as TOTAL_REVENUE_POTENTIAL
FROM 
  TOURISM_ADMIN.FACT_ACCOMMODATION fa
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fa.ACCOMMODATION_ID = d.ACCOMMODATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_DATE dd ON fa.DATE_ID = dd.DATE_ID;

-- OLAP View 5: Top Performers Ranking
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_TOP_PERFORMERS AS
SELECT 
  d.HOTEL_NAME,
  d.STAR_RATING,
  d.ROOM_TYPE,
  COUNT(*) as TOTAL_BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_EUR) as TOTAL_REVENUE_EUR,
  ROUND(AVG(fb.TOTAL_AMOUNT_EUR), 2) as AVG_BOOKING_EUR,
  ROW_NUMBER() OVER (ORDER BY SUM(fb.TOTAL_AMOUNT_EUR) DESC) as REVENUE_RANK,
  ROUND(100 * SUM(fb.TOTAL_AMOUNT_EUR) / SUM(SUM(fb.TOTAL_AMOUNT_EUR)) OVER (), 2) as REVENUE_PERCENTAGE
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
GROUP BY 
  d.HOTEL_NAME, d.STAR_RATING, d.ROOM_TYPE
ORDER BY 
  TOTAL_REVENUE_EUR DESC;

-- OLAP View 6: Multi-Dimensional Analysis
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_MULTIDIM AS
SELECT 
  d.STAR_RATING,
  d.HOTEL_NAME,
  loc.CITY,
  loc.COUNTRY,
  cur.CURRENCY_CODE,
  cur.EUR_RATE,
  COUNT(*) as BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_LOCAL) as REVENUE_LOCAL,
  SUM(fb.TOTAL_AMOUNT_EUR) as REVENUE_EUR,
  ROUND(SUM(fb.NIGHTS_COUNT) / COUNT(*), 1) as AVG_NIGHTS_PER_BOOKING,
  ROUND(SUM(fb.TOTAL_AMOUNT_EUR) / NULLIF(SUM(fb.NIGHTS_COUNT), 0), 2) as REVENUE_PER_NIGHT_EUR
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_LOCATION loc ON fb.LOCATION_ID = loc.LOCATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_CURRENCY cur ON fb.CURRENCY_ID = cur.CURRENCY_ID
GROUP BY 
  d.STAR_RATING, d.HOTEL_NAME, loc.CITY, loc.COUNTRY, cur.CURRENCY_CODE, cur.EUR_RATE;

-- OLAP View 7: Geographic Revenue Heatmap
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_ANALYTICS_GEOGRAPHIC_HEATMAP AS
SELECT 
  loc.COUNTRY,
  loc.CITY,
  loc.LATITUDE,
  loc.LONGITUDE,
  COUNT(*) as BOOKING_COUNT,
  SUM(fb.TOTAL_AMOUNT_EUR) as TOTAL_REVENUE_EUR,
  ROUND(AVG(fb.TOTAL_AMOUNT_EUR), 2) as AVG_BOOKING_EUR,
  RANK() OVER (ORDER BY SUM(fb.TOTAL_AMOUNT_EUR) DESC) as CITY_REVENUE_RANK,
  ROUND(100 * SUM(fb.TOTAL_AMOUNT_EUR) / SUM(SUM(fb.TOTAL_AMOUNT_EUR)) OVER (), 2) as REVENUE_SHARE_PCT
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_LOCATION loc ON fb.LOCATION_ID = loc.LOCATION_ID
GROUP BY 
  loc.COUNTRY, loc.CITY, loc.LATITUDE, loc.LONGITUDE
ORDER BY 
  TOTAL_REVENUE_EUR DESC;

COMMIT;

PROMPT OLAP analytical views created

-- ============================================================================
-- REPORTING LAYER - Business Intelligence Views
-- ============================================================================

PROMPT [5] Creating Business Intelligence Reporting Views...

-- BI Report 1: Executive Summary
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_REPORT_EXECUTIVE_SUMMARY AS
SELECT 
  'Platform Metrics' as REPORT_CATEGORY,
  'Total Bookings' as METRIC_NAME,
  NULL as DESCRIPTION,
  COUNT(*) as METRIC_VALUE
FROM TOURISM_ADMIN.FACT_BOOKINGS
UNION ALL
SELECT 'Platform Metrics', 'Confirmed Bookings', NULL, 
  SUM(CASE WHEN BOOKING_STATUS = 'CONFIRMED' THEN 1 ELSE 0 END)
FROM TOURISM_ADMIN.FACT_BOOKINGS
UNION ALL
SELECT 'Platform Metrics', 'Hotels Active', NULL, COUNT(DISTINCT ACCOMMODATION_ID)
FROM TOURISM_ADMIN.FACT_BOOKINGS
UNION ALL
SELECT 'Platform Metrics', 'Avg Booking Value (EUR)', NULL, ROUND(AVG(TOTAL_AMOUNT_EUR), 2)
FROM TOURISM_ADMIN.FACT_BOOKINGS;

-- BI Report 2: Revenue Analysis
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_REPORT_REVENUE_ANALYSIS AS
SELECT 
  d.HOTEL_NAME,
  d.STAR_RATING,
  COUNT(*) as BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_EUR) as REVENUE_EUR,
  ROUND(AVG(fb.TOTAL_AMOUNT_EUR), 2) as AVG_BOOKING_EUR,
  ROUND(100.0 * SUM(fb.TOTAL_AMOUNT_EUR) / (SELECT SUM(TOTAL_AMOUNT_EUR) FROM TOURISM_ADMIN.FACT_BOOKINGS), 2) as REVENUE_SHARE_PCT
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
GROUP BY 
  d.HOTEL_NAME, d.STAR_RATING;

-- BI Report 3: Geographic Performance
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_REPORT_GEOGRAPHIC AS
SELECT 
  loc.COUNTRY,
  loc.CITY,
  COUNT(*) as BOOKINGS,
  SUM(fb.TOTAL_AMOUNT_EUR) as REVENUE_EUR,
  ROUND(AVG(fb.TOTAL_AMOUNT_EUR), 2) as AVG_VALUE_EUR,
  MAX(d.STAR_RATING) as TOP_STAR_RATING
FROM 
  TOURISM_ADMIN.FACT_BOOKINGS fb
  INNER JOIN TOURISM_ADMIN.DIM_LOCATION loc ON fb.LOCATION_ID = loc.LOCATION_ID
  INNER JOIN TOURISM_ADMIN.DIM_ACCOMMODATION d ON fb.ACCOMMODATION_ID = d.ACCOMMODATION_ID
GROUP BY 
  loc.COUNTRY, loc.CITY;

COMMIT;

-- ============================================================================
-- VERIFICATION AND REPORTING
-- ========================================================================

PROMPT
PROMPT ========================================================================
PROMPT TEMA L3: OLAP ANALYTICAL LAYER - IMPLEMENTATION COMPLETE
PROMPT ========================================================================
PROMPT

PROMPT [CONSOLIDATION VIEWS]
PROMPT 1. V_CONSOLIDATE_BOOKINGS - Multi-source booking data
PROMPT 2. V_CONSOLIDATE_ACCOMMODATION - Room inventory with rates
PROMPT 3. V_CONSOLIDATE_TRAVEL - Bookings integrated with flights
PROMPT Created: 3 consolidation views
PROMPT

PROMPT [DIMENSIONAL TABLES]
PROMPT 1. DIM_DATE ................ 7 date records
SELECT COUNT(*) FROM TOURISM_ADMIN.DIM_DATE;
PROMPT 2. DIM_LOCATION ........... 5 location records
SELECT COUNT(*) FROM TOURISM_ADMIN.DIM_LOCATION;
PROMPT 3. DIM_ACCOMMODATION ...... 5 accommodation records
SELECT COUNT(*) FROM TOURISM_ADMIN.DIM_ACCOMMODATION;
PROMPT 4. DIM_CURRENCY ........... 5 currency records
SELECT COUNT(*) FROM TOURISM_ADMIN.DIM_CURRENCY;
PROMPT 5. DIM_TRANSPORT .......... 3 transport records
SELECT COUNT(*) FROM TOURISM_ADMIN.DIM_TRANSPORT;
PROMPT

PROMPT [FACT TABLES]
PROMPT 1. FACT_BOOKINGS .......... 2 booking records
SELECT COUNT(*) FROM TOURISM_ADMIN.FACT_BOOKINGS;
PROMPT 2. FACT_ACCOMMODATION .... 2 accommodation records
SELECT COUNT(*) FROM TOURISM_ADMIN.FACT_ACCOMMODATION;
PROMPT

PROMPT [OLAP ANALYTICAL VIEWS]
PROMPT  ✓ V_ANALYTICS_REVENUE_ROLLUP - Revenue hierarchy (ROLLUP)
PROMPT  ✓ V_ANALYTICS_LOCATION_CUBE - Location multidimensional (CUBE)
PROMPT  ✓ V_ANALYTICS_TEMPORAL_TREND - Time series (Window Functions)
PROMPT  ✓ V_ANALYTICS_OCCUPANCY - Occupancy trends (Moving Avg, Lead/Lag)
PROMPT  ✓ V_ANALYTICS_TOP_PERFORMERS - Rankings (ROW_NUMBER, Percentages)
PROMPT  ✓ V_ANALYTICS_MULTIDIM - Multi-dimensional aggregates
PROMPT  ✓ V_ANALYTICS_GEOGRAPHIC_HEATMAP - Regional revenue analysis
PROMPT Created: 7 OLAP analytical views
PROMPT

PROMPT [BUSINESS INTELLIGENCE REPORTS]
PROMPT  ✓ V_REPORT_EXECUTIVE_SUMMARY - Key metrics dashboard
PROMPT  ✓ V_REPORT_REVENUE_ANALYSIS - Revenue by hotel
PROMPT  ✓ V_REPORT_GEOGRAPHIC - Geographic performance
PROMPT Created: 3 BI reporting views
PROMPT

PROMPT ========================================================================
PROMPT SAMPLE OUTPUT: OLAP QUERIES
PROMPT ========================================================================
PROMPT

PROMPT [1] REVENUE ROLLUP - Hotels by Stars by Room Types:
SELECT * FROM TOURISM_ADMIN.V_ANALYTICS_REVENUE_ROLLUP;

PROMPT
PROMPT [2] LOCATION CUBE - Multidimensional Analysis:
SELECT * FROM TOURISM_ADMIN.V_ANALYTICS_LOCATION_CUBE;

PROMPT
PROMPT [3] REVENUE TOP PERFORMERS:
SELECT HOTEL_NAME, TOTAL_REVENUE_EUR, REVENUE_RANK, REVENUE_PERCENTAGE
FROM TOURISM_ADMIN.V_ANALYTICS_TOP_PERFORMERS;

PROMPT
PROMPT [4] GEOGRAPHIC REVENUE HEATMAP:
SELECT COUNTRY, CITY, BOOKING_COUNT, TOTAL_REVENUE_EUR, REVENUE_SHARE_PCT
FROM TOURISM_ADMIN.V_ANALYTICS_GEOGRAPHIC_HEATMAP;

PROMPT
PROMPT [5] EXECUTIVE SUMMARY:
SELECT * FROM TOURISM_ADMIN.V_REPORT_EXECUTIVE_SUMMARY;

PROMPT
PROMPT [6] GEOGRAPHIC PERFORMANCE:
SELECT * FROM TOURISM_ADMIN.V_REPORT_GEOGRAPHIC;

PROMPT
PROMPT ========================================================================
PROMPT TEMA L3: COMPLETED SUCCESSFULLY ✓
PROMPT ========================================================================
PROMPT
PROMPT Implementation Summary:
PROMPT
PROMPT  ✓ Consolidation Layer: 3 views (multi-source joins)
PROMPT  ✓ Dimensional Tables: 5 dimensions (25 total records)
PROMPT  ✓ Fact Tables: 2 fact tables (4 total records)
PROMPT  ✓ OLAP Views: 7 analytical views
PROMPT    - ROLLUP: Revenue hierarchy
PROMPT    - CUBE: Multi-dimensional analysis
PROMPT    - Window Functions: Temporal trends, moving averages, rankings
PROMPT    - Analytical Functions: RANK, DENSE_RANK, ROW_NUMBER
PROMPT    - Aggregate Functions: SUM, COUNT, AVG, MAX/MIN
PROMPT  ✓ BI Reports: 3 reporting views
PROMPT
PROMPT Analytical Capabilities:
PROMPT  [✓] Hierarchical aggregation (ROLLUP)
PROMPT  [✓] Multi-dimensional analysis (CUBE)
PROMPT  [✓] Window-based computations (running totals, moving averages)
PROMPT  [✓] Advanced ranking and analytics
PROMPT  [✓] Geographic and temporal analysis
PROMPT  [✓] Executive reporting layer
PROMPT
PROMPT Database Objects: 18 objects total
PROMPT   - 3 Consolidation Views
PROMPT   - 5 Dimensional Tables
PROMPT   - 2 Fact Tables
PROMPT   - 7 OLAP Analytical Views
PROMPT   - 1 BI Summary
PROMPT
PROMPT ========================================================================

EXIT;
