-- ============================================================================
-- Create tourism schema for TOURISM_ADMIN user
-- Executed as SYSTEM with schema-qualified objects
-- ============================================================================

ALTER SESSION SET CONTAINER=FREEPDB1;

-- ============================================================================
-- PART 1: CREATE BASE TABLES IN TOURISM_ADMIN SCHEMA
-- ============================================================================

CREATE TABLE TOURISM_ADMIN.REGIONS (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(100) NOT NULL,
    REGION_CODE VARCHAR2(10),
    POPULATION NUMBER,
    GDP DECIMAL(18,2),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE TOURISM_ADMIN.DESTINATIONS (
    DESTINATION_ID NUMBER PRIMARY KEY,
    REGION_ID NUMBER REFERENCES TOURISM_ADMIN.REGIONS(REGION_ID),
    NAME VARCHAR2(200) NOT NULL,
    TYPE VARCHAR2(50),
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    VISITORS_ANNUAL NUMBER,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE TOURISM_ADMIN.HOTELS (
    HOTEL_ID NUMBER PRIMARY KEY,
    DESTINATION_ID NUMBER REFERENCES TOURISM_ADMIN.DESTINATIONS(DESTINATION_ID),
    NAME VARCHAR2(200) NOT NULL,
    STARS NUMBER,
    ROOMS_TOTAL NUMBER,
    ROOMS_AVAILABLE NUMBER,
    PRICE_PER_NIGHT DECIMAL(10,2),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE TOURISM_ADMIN.BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    HOTEL_ID NUMBER REFERENCES TOURISM_ADMIN.HOTELS(HOTEL_ID),
    BOOKING_DATE TIMESTAMP,
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    GUEST_NAME VARCHAR2(200),
    TOTAL_COST DECIMAL(12,2),
    STATUS VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE TOURISM_ADMIN.FLIGHTS (
    FLIGHT_ID NUMBER PRIMARY KEY,
    AIRLINE_CODE VARCHAR2(10),
    FLIGHT_NUMBER VARCHAR2(20),
    ORIGIN_AIRPORT VARCHAR2(10),
    DESTINATION_AIRPORT VARCHAR2(10),
    DEPARTURE_TIME TIMESTAMP,
    ARRIVAL_TIME TIMESTAMP,
    AIRCRAFT_TYPE VARCHAR2(50),
    PASSENGERS_COUNT NUMBER,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

PROMPT Tables created successfully!

-- ============================================================================
-- PART 2: CREATE SEQUENCES
-- ============================================================================

CREATE SEQUENCE TOURISM_ADMIN.SEQ_REGION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURISM_ADMIN.SEQ_DESTINATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURISM_ADMIN.SEQ_HOTEL_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURISM_ADMIN.SEQ_BOOKING_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TOURISM_ADMIN.SEQ_FLIGHT_ID START WITH 1 INCREMENT BY 1;

PROMPT Sequences created!

-- ============================================================================
-- PART 3: INSERT SAMPLE DATA
-- ============================================================================

INSERT INTO TOURISM_ADMIN.REGIONS VALUES (1, 'Transylvania', 'TRANS', 2500000, 45000000000);
INSERT INTO TOURISM_ADMIN.REGIONS VALUES (2, 'Bukovina', 'BUK', 1000000, 15000000000);
INSERT INTO TOURISM_ADMIN.REGIONS VALUES (3, 'Dobruja', 'DOB', 800000, 12000000000);

INSERT INTO TOURISM_ADMIN.DESTINATIONS VALUES (1, 1, 'Brașov', 'Mountain City', 45.6408, 24.5666, 250000);
INSERT INTO TOURISM_ADMIN.DESTINATIONS VALUES (2, 1, 'Bran Castle', 'Historical Site', 45.5096, 25.3858, 400000);
INSERT INTO TOURISM_ADMIN.DESTINATIONS VALUES (3, 2, 'Suceava', 'Medieval Town', 47.6500, 26.2600, 150000);

INSERT INTO TOURISM_ADMIN.HOTELS VALUES (1, 1, 'Postillion Brașov', 4, 85, 10, 150.00);
INSERT INTO TOURISM_ADMIN.HOTELS VALUES (2, 1, 'Spa Hotel & Wellness', 5, 120, 5, 280.00);
INSERT INTO TOURISM_ADMIN.HOTELS VALUES (3, 2, 'Castel Hotel Bran', 4, 45, 8, 180.00);

INSERT INTO TOURISM_ADMIN.FLIGHTS VALUES (1, 'RO', 'RO1234', 'BUH', 'PRG', 
        TO_TIMESTAMP('2026-04-06 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-04-06 10:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Boeing 737', 180);

INSERT INTO TOURISM_ADMIN.FLIGHTS VALUES (2, 'RO', 'RO5678', 'OTP', 'VIE',
        TO_TIMESTAMP('2026-04-06 12:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-04-06 13:45:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Airbus A320', 165);

COMMIT;
PROMPT Sample data inserted!

-- ============================================================================
-- PART 4: CREATE VIEWS
-- ============================================================================

CREATE VIEW TOURISM_ADMIN.V_HOTELS_BY_DESTINATION AS
SELECT 
    d.DESTINATION_ID,
    d.NAME AS DESTINATION_NAME,
    d.VISITORS_ANNUAL,
    COUNT(h.HOTEL_ID) AS HOTEL_COUNT,
    AVG(h.STARS) AS AVG_STARS,
    AVG(h.PRICE_PER_NIGHT) AS AVG_PRICE
FROM TOURISM_ADMIN.DESTINATIONS d
LEFT JOIN TOURISM_ADMIN.HOTELS h ON d.DESTINATION_ID = h.DESTINATION_ID
GROUP BY d.DESTINATION_ID, d.NAME, d.VISITORS_ANNUAL;

CREATE VIEW TOURISM_ADMIN.V_TOURISM_BY_REGION AS
SELECT
    r.REGION_ID,
    r.REGION_NAME,
    COUNT(DISTINCT d.DESTINATION_ID) AS DESTINATIONS,
    COUNT(DISTINCT h.HOTEL_ID) AS HOTELS,
    SUM(h.ROOMS_TOTAL) AS TOTAL_ROOMS,
    AVG(d.VISITORS_ANNUAL) AS AVG_VISITORS
FROM TOURISM_ADMIN.REGIONS r
LEFT JOIN TOURISM_ADMIN.DESTINATIONS d ON r.REGION_ID = d.REGION_ID
LEFT JOIN TOURISM_ADMIN.HOTELS h ON d.DESTINATION_ID = h.DESTINATION_ID
GROUP BY r.REGION_ID, r.REGION_NAME;

PROMPT Views created!

-- ============================================================================
-- VERIFICATION
-- ============================================================================

PROMPT
PROMPT ========================================================================
PROMPT DEPLOYMENT COMPLETE - Tourism Analytics Platform Ready
PROMPT ========================================================================
PROMPT

PROMPT Tables in TOURISM_ADMIN schema:
SELECT TABLE_NAME, NUM_ROWS FROM USER_TABLES WHERE OWNER = 'TOURISM_ADMIN' ORDER BY TABLE_NAME;

PROMPT
PROMPT Views in TOURISM_ADMIN schema:
SELECT VIEW_NAME FROM USER_VIEWS WHERE OWNER = 'TOURISM_ADMIN' ORDER BY VIEW_NAME;

PROMPT
PROMPT Sample Query - Tourism by Region:
SELECT * FROM TOURISM_ADMIN.V_TOURISM_BY_REGION;

PROMPT
PROMPT ========================================================================
PROMPT Setup Complete! Database is ready for use.
PROMPT Connection: sqlplus TOURISM_ADMIN/Tourism2025@FREE
PROMPT ========================================================================
PROMPT

COMMIT;
EXIT;
