-- ============================================================================
-- Simplified TEMA L2/L3 Deployment for Tourism Analysis Platform
-- Minimal setup for demonstration
-- ============================================================================

-- ============================================================================
-- PART 1: CREATE BASE TABLES
-- ============================================================================

CREATE TABLE REGIONS (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(100) NOT NULL,
    REGION_CODE VARCHAR2(10),
    POPULATION NUMBER,
    GDP DECIMAL(18,2),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE DESTINATIONS (
    DESTINATION_ID NUMBER PRIMARY KEY,
    REGION_ID NUMBER REFERENCES REGIONS(REGION_ID),
    NAME VARCHAR2(200) NOT NULL,
    TYPE VARCHAR2(50),
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    VISITORS_ANNUAL NUMBER,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE HOTELS (
    HOTEL_ID NUMBER PRIMARY KEY,
    DESTINATION_ID NUMBER REFERENCES DESTINATIONS(DESTINATION_ID),
    NAME VARCHAR2(200) NOT NULL,
    STARS NUMBER,
    ROOMS_TOTAL NUMBER,
    ROOMS_AVAILABLE NUMBER,
    PRICE_PER_NIGHT DECIMAL(10,2),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    HOTEL_ID NUMBER REFERENCES HOTELS(HOTEL_ID),
    BOOKING_DATE TIMESTAMP,
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    GUEST_NAME VARCHAR2(200),
    TOTAL_COST DECIMAL(12,2),
    STATUS VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE FLIGHTS (
    FLIGHT_ID NUMBER PRIMARY KEY,
    AIRLINE_CODE VARCHAR2(10),
    FLIGHT_NUMBER VARCHAR2(20),
    ORIGIN_AIRPORT VARCHAR2(10),
    DESTINATION_AIRPORT VARCHAR2(10),
    DEPARTURE_TIME TIMESTAMP,
    ARRIVAL_TIME TIMESTAMP,
    AIRCRAFT_TYPE VARCHAR2(50),
    PASSENGERS_COUNT NUMBER,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

-- ============================================================================
-- PART 2: CREATE SEQUENCES FOR AUTO-INCREMENT
-- ============================================================================

CREATE SEQUENCE SEQ_REGION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DESTINATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HOTEL_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOOKING_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FLIGHT_ID START WITH 1 INCREMENT BY 1;

-- ============================================================================
-- PART 3: INSERT SAMPLE DATA
-- ============================================================================

INSERT INTO REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP)
VALUES (1, 'Transylvania', 'TRANS', 2500000, 45000000000);

INSERT INTO REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP)
VALUES (2, 'Bukovina', 'BUK', 1000000, 15000000000);

INSERT INTO REGIONS (REGION_ID, REGION_NAME, REGION_CODE, POPULATION, GDP)
VALUES (3, 'Dobruja', 'DOB', 800000, 12000000000);

INSERT INTO DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL)
VALUES (1, 1, 'Brașov', 'Mountain City', 45.6408, 24.5666, 250000);

INSERT INTO DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL)
VALUES (2, 1, 'Bran Castle', 'Historical Site', 45.5096, 25.3858, 400000);

INSERT INTO DESTINATIONS (DESTINATION_ID, REGION_ID, NAME, TYPE, LATITUDE, LONGITUDE, VISITORS_ANNUAL)
VALUES (3, 2, 'Suceava', 'Medieval Town', 47.6500, 26.2600, 150000);

INSERT INTO HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT)
VALUES (1, 1, 'Postillion Brașov', 4, 85, 10, 150.00);

INSERT INTO HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT)
VALUES (2, 1, 'Spa Hotel & Wellness', 5, 120, 5, 280.00);

INSERT INTO HOTELS (HOTEL_ID, DESTINATION_ID, NAME, STARS, ROOMS_TOTAL, ROOMS_AVAILABLE, PRICE_PER_NIGHT)
VALUES (3, 2, 'Castel Hotel Bran', 4, 45, 8, 180.00);

INSERT INTO FLIGHTS (FLIGHT_ID, AIRLINE_CODE, FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, 
                     DEPARTURE_TIME, ARRIVAL_TIME, AIRCRAFT_TYPE, PASSENGERS_COUNT)
VALUES (1, 'RO', 'RO1234', 'BUH', 'PRG', 
        TO_TIMESTAMP('2026-04-06 08:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-04-06 10:15:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Boeing 737', 180);

INSERT INTO FLIGHTS (FLIGHT_ID, AIRLINE_CODE, FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT,
                     DEPARTURE_TIME, ARRIVAL_TIME, AIRCRAFT_TYPE, PASSENGERS_COUNT)
VALUES (2, 'RO', 'RO5678', 'OTP', 'VIE',
        TO_TIMESTAMP('2026-04-06 12:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-04-06 13:45:00', 'YYYY-MM-DD HH24:MI:SS'),
        'Airbus A320', 165);

COMMIT;

-- ============================================================================
-- PART 4: CREATE VIEWS FOR ANALYTICS
-- ============================================================================

-- View: Hotels by destination with average rating
CREATE VIEW V_HOTELS_BY_DESTINATION AS
SELECT 
    d.DESTINATION_ID,
    d.NAME AS DESTINATION_NAME,
    d.VISITORS_ANNUAL,
    COUNT(h.HOTEL_ID) AS HOTEL_COUNT,
    AVG(h.STARS) AS AVG_STARS,
    AVG(h.PRICE_PER_NIGHT) AS AVG_PRICE
FROM DESTINATIONS d
LEFT JOIN HOTELS h ON d.DESTINATION_ID = h.DESTINATION_ID
GROUP BY d.DESTINATION_ID, d.NAME, d.VISITORS_ANNUAL;

-- View: Bookings summary by hotel
CREATE VIEW V_BOOKINGS_BY_HOTEL AS
SELECT
    h.HOTEL_ID,
    h.NAME AS HOTEL_NAME,
    d.NAME AS DESTINATION_NAME,
    COUNT(b.BOOKING_ID) AS TOTAL_BOOKINGS,
    SUM(b.TOTAL_COST) AS TOTAL_REVENUE,
    AVG(b.TOTAL_COST) AS AVG_BOOKING_VALUE
FROM HOTELS h
LEFT JOIN DESTINATIONS d ON h.DESTINATION_ID = d.DESTINATION_ID
LEFT JOIN BOOKINGS b ON h.HOTEL_ID = b.HOTEL_ID AND b.STATUS = 'CONFIRMED'
GROUP BY h.HOTEL_ID, h.NAME, d.NAME;

-- View: Tourism statistics by region
CREATE VIEW V_TOURISM_BY_REGION AS
SELECT
    r.REGION_ID,
    r.REGION_NAME,
    COUNT(DISTINCT d.DESTINATION_ID) AS DESTINATIONS,
    COUNT(DISTINCT h.HOTEL_ID) AS HOTELS,
    SUM(h.ROOMS_TOTAL) AS TOTAL_ROOMS,
    AVG(d.VISITORS_ANNUAL) AS AVG_VISITORS
FROM REGIONS r
LEFT JOIN DESTINATIONS d ON r.REGION_ID = d.REGION_ID
LEFT JOIN HOTELS h ON d.DESTINATION_ID = h.DESTINATION_ID
GROUP BY r.REGION_ID, r.REGION_NAME;

-- ============================================================================
-- PART 5: VERIFICATION QUERIES
-- ============================================================================

PROMPT
PROMPT ========================================================================
PROMPT TEMA L2/L3 Simplified Deployment - Verification Report
PROMPT ========================================================================
PROMPT

PROMPT [TABLE CREATION] Regions:
SELECT COUNT(*) AS REGION_COUNT FROM REGIONS;

PROMPT [TABLE CREATION] Destinations:
SELECT COUNT(*) AS DESTINATION_COUNT FROM DESTINATIONS;

PROMPT [TABLE CREATION] Hotels:
SELECT COUNT(*) AS HOTEL_COUNT FROM HOTELS;

PROMPT [TABLE CREATION] Flights:
SELECT COUNT(*) AS FLIGHT_COUNT FROM FLIGHTS;

PROMPT [VIEWS CREATED]:
SELECT COUNT(*) AS VIEW_COUNT FROM USER_VIEWS WHERE VIEW_NAME LIKE 'V_%';

PROMPT [DATA VERIFICATION] Hotels by Destination View:
SELECT * FROM V_HOTELS_BY_DESTINATION;

PROMPT [DATA VERIFICATION] Bookings by Hotel View:
SELECT * FROM V_BOOKINGS_BY_HOTEL;

PROMPT [DATA VERIFICATION] Tourism by Region View:
SELECT * FROM V_TOURISM_BY_REGION;

PROMPT
PROMPT ========================================================================
PROMPT Deployment Complete - Database ready for analytics!
PROMPT ========================================================================
PROMPT

COMMIT;
EXIT;
