-- TEMA L2: Simplified Federation Views - Direct Creation
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Create federation views as system in tourism_admin schema
CREATE OR REPLACE VIEW TOURISM_ADMIN.V_DS1_HOTELS AS
SELECT 
  h.HOTEL_ID,
  h.HOTEL_NAME,
  h.CITY,
  h.COUNTRY,
  h.STAR_RATING,
  h.TOTAL_ROOMS,
  h.YEAR_OPENED,
  'DS_1_HOTELS' as SOURCE_SYSTEM,
  'DIRECT_TABLE' as ACCESS_MECHANISM
FROM DS1_HOTELS.HOTELS h;

CREATE OR REPLACE VIEW TOURISM_ADMIN.V_DS1_ROOMS AS
SELECT 
  rt.ROOM_TYPE_ID,
  h.HOTEL_ID,
  h.HOTEL_NAME,
  rt.ROOM_TYPE,
  rt.CAPACITY,
  rt.NIGHTLY_RATE,
  rt.AVAILABLE_ROOMS,
  rt.CURRENCY,
  'DS_1_HOTELS' as SOURCE_SYSTEM,
  'DIRECT_TABLE' as ACCESS_MECHANISM
FROM DS1_HOTELS.HOTELS h
INNER JOIN DS1_HOTELS.ROOM_TYPES rt ON h.HOTEL_ID = rt.HOTEL_ID;

CREATE OR REPLACE VIEW TOURISM_ADMIN.V_DS1_BOOKINGS AS
SELECT 
  bk.BOOKING_ID,
  h.HOTEL_ID,
  h.HOTEL_NAME,
  bk.GUEST_NAME,
  bk.CHECK_IN_DATE,
  bk.CHECK_OUT_DATE,
  bk.NIGHTS,
  bk.TOTAL_PRICE,
  bk.BOOKING_STATUS,
  'DS_1_HOTELS' as SOURCE_SYSTEM,
  'DIRECT_TABLE' as ACCESS_MECHANISM
FROM DS1_HOTELS.HOTELS h
INNER JOIN DS1_HOTELS.BOOKINGS_HISTORY bk ON h.HOTEL_ID = bk.HOTEL_ID;

CREATE OR REPLACE VIEW TOURISM_ADMIN.V_DS2_FLIGHTS AS
SELECT 
  F.FLIGHT_ID,
  F.ICAO24,
  F.CALLSIGN,
  F.ORIGIN_COUNTRY,
  F.ORIGIN_AIRPORT,
  F.DESTINATION_AIRPORT,
  F.LATITUDE,
  F.LONGITUDE,
  F.ALTITUDE_M,
  F.VELOCITY_MS,
  F.CAPTURE_TIME,
  'DS_2_OPENSKY' as SOURCE_SYSTEM,
  'REST_API' as ACCESS_MECHANISM
FROM TOURISM_ADMIN.DS2_FLIGHTS_CACHE F;

CREATE OR REPLACE VIEW TOURISM_ADMIN.V_DS3_CURRENCY_RATES AS
SELECT 
  C.CURRENCY_CODE,
  C.CURRENCY_NAME,
  C.EUR_RATE,
  C.RATE_DATE,
  C.SOURCE,
  C.LAST_UPDATE,
  'DS_3_ECB' as SOURCE_SYSTEM,
  'HTTP_XML' as ACCESS_MECHANISM
FROM TOURISM_ADMIN.DS3_CURRENCY_RATES C;

CREATE OR REPLACE VIEW TOURISM_ADMIN.V_FEDERATION_SUMMARY AS
SELECT 
  'Hotels (DS_1)' as DATA_SOURCE,
  (SELECT COUNT(DISTINCT HOTEL_ID) FROM DS1_HOTELS.HOTELS) as RECORD_COUNT,
  'Direct Table Access' as ACCESS_METHOD,
  SYSDATE as SYNC_TIME
FROM DUAL
UNION ALL
SELECT 
  'Flights (DS_2)',
  (SELECT COUNT(*) FROM TOURISM_ADMIN.DS2_FLIGHTS_CACHE),
  'REST API Cache',
  SYSDATE
FROM DUAL
UNION ALL
SELECT 
  'Currencies (DS_3)',
  (SELECT COUNT(*) FROM TOURISM_ADMIN.DS3_CURRENCY_RATES),
  'HTTP XML Feed',
  SYSDATE
FROM DUAL;

COMMIT;

-- Verify
PROMPT
PROMPT ========================================================================
PROMPT TEMA L2: FEDERATED ARCHITECTURE - DEPLOYMENT COMPLETE ✓
PROMPT ========================================================================
PROMPT

PROMPT [FEDERATION STATUS] Data Sources Available:
SELECT * FROM TOURISM_ADMIN.V_FEDERATION_SUMMARY;

PROMPT
PROMPT [DS_1 HOTELS] External Accommodation Source (3 Hotels):
SELECT HOTEL_NAME, CITY, STAR_RATING, TOTAL_ROOMS
FROM TOURISM_ADMIN.V_DS1_HOTELS;

PROMPT
PROMPT [DS_1] Room Types (4 Different Room Configurations):
SELECT HOTEL_NAME, ROOM_TYPE, CAPACITY, NIGHTLY_RATE, CURRENCY
FROM TOURISM_ADMIN.V_DS1_ROOMS;

PROMPT
PROMPT [DS_1] Booking Records (2 Confirmed Bookings):
SELECT BOOKING_ID, HOTEL_NAME, GUEST_NAME, CHECK_IN_DATE, TOTAL_PRICE
FROM TOURISM_ADMIN.V_DS1_BOOKINGS;

PROMPT
PROMPT [DS_2 FLIGHTS] Live Flight Data (3 Active Flights):
SELECT CALLSIGN, ORIGIN_COUNTRY, ORIGIN_AIRPORT, DESTINATION_AIRPORT, ALTITUDE_M
FROM TOURISM_ADMIN.V_DS2_FLIGHTS;

PROMPT
PROMPT [DS_3 CURRENCY] Exchange Rates (5 Currencies):
SELECT CURRENCY_CODE, CURRENCY_NAME, EUR_RATE, SOURCE
FROM TOURISM_ADMIN.V_DS3_CURRENCY_RATES;

PROMPT
PROMPT ========================================================================
PROMPT TEMA L2 IMPLEMENTATION COMPLETE
PROMPT ========================================================================
PROMPT Summary:
PROMPT  ✓ DS_1: Hotels  - Direct Table Access (3 external hotels)
PROMPT  ✓ DS_2: Flights - REST API Integration (3 live flights)
PROMPT  ✓ DS_3: Currency - HTTP XML Web Service (5 exchange rates)
PROMPT  ✓ Federation Views - Unified data access layer
PROMPT  ✓ Access Mechanisms - 3 different federation patterns implemented
PROMPT  ✓ Users Created - L2_FEDERATION, DS1_HOTELS for federation
PROMPT ========================================================================

EXIT;
