-- Verify and fix TEMA L2 data inserts
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Check what's in the tables
PROMPT Current state of DS_1 tables:
PROMPT Hotels:
SELECT COUNT(*) as HOTEL_COUNT FROM TOURISM_ADMIN.HOTELS_DS1;

-- Reinserting DS_1 data with explicit commits
PROMPT
PROMPT Re-inserting DS_1 data...

DELETE FROM TOURISM_ADMIN.BOOKINGS_DS1;
DELETE FROM TOURISM_ADMIN.ROOM_TYPES_DS1;
DELETE FROM TOURISM_ADMIN.HOTELS_DS1;
COMMIT;

INSERT INTO TOURISM_ADMIN.HOTELS_DS1 (HOTEL_ID, HOTEL_NAME, CITY, COUNTRY, STAR_RATING, TOTAL_ROOMS, YEAR_OPENED)
VALUES (101, 'Intercontinental Bucharest', 'Bucharest', 'Romania', 5, 250, 1979);

INSERT INTO TOURISM_ADMIN.HOTELS_DS1 (HOTEL_ID, HOTEL_NAME, CITY, COUNTRY, STAR_RATING, TOTAL_ROOMS, YEAR_OPENED)
VALUES (102, 'Radisson Blu Brașov', 'Brașov', 'Romania', 4, 180, 2009);

INSERT INTO TOURISM_ADMIN.HOTELS_DS1 (HOTEL_ID, HOTEL_NAME, CITY, COUNTRY, STAR_RATING, TOTAL_ROOMS, YEAR_OPENED)
VALUES (103, 'Hotel Tâmpa', 'Brașov', 'Romania', 3, 45, 1995);

COMMIT;

INSERT INTO TOURISM_ADMIN.ROOM_TYPES_DS1 (ROOM_TYPE_ID, HOTEL_ID, ROOM_TYPE, CAPACITY, NIGHTLY_RATE, AVAILABLE_ROOMS, CURRENCY)
VALUES (1001, 101, 'Deluxe Suite', 2, 380.00, 15, 'USD');

INSERT INTO TOURISM_ADMIN.ROOM_TYPES_DS1 (ROOM_TYPE_ID, HOTEL_ID, ROOM_TYPE, CAPACITY, NIGHTLY_RATE, AVAILABLE_ROOMS, CURRENCY)
VALUES (1002, 101, 'Standard Room', 2, 220.00, 50, 'USD');

INSERT INTO TOURISM_ADMIN.ROOM_TYPES_DS1 (ROOM_TYPE_ID, HOTEL_ID, ROOM_TYPE, CAPACITY, NIGHTLY_RATE, AVAILABLE_ROOMS, CURRENCY)
VALUES (1003, 102, 'Executive Suite', 2, 300.00, 8, 'EUR');

INSERT INTO TOURISM_ADMIN.ROOM_TYPES_DS1 (ROOM_TYPE_ID, HOTEL_ID, ROOM_TYPE, CAPACITY, NIGHTLY_RATE, AVAILABLE_ROOMS, CURRENCY)
VALUES (1004, 102, 'Standard Room', 2, 150.00, 35, 'EUR');

COMMIT;

INSERT INTO TOURISM_ADMIN.BOOKINGS_DS1 (BOOKING_ID, HOTEL_ID, GUEST_NAME, CHECK_IN_DATE, CHECK_OUT_DATE, NIGHTS, ROOM_TYPE, TOTAL_PRICE, BOOKING_STATUS)
VALUES ('BK001', 101, 'John Smith', TO_DATE('2026-04-10', 'yyyy-mm-dd'), TO_DATE('2026-04-12', 'yyyy-mm-dd'), 2, 'Deluxe Suite', 760.00, 'CONFIRMED');

INSERT INTO TOURISM_ADMIN.BOOKINGS_DS1 (BOOKING_ID, HOTEL_ID, GUEST_NAME, CHECK_IN_DATE, CHECK_OUT_DATE, NIGHTS, ROOM_TYPE, TOTAL_PRICE, BOOKING_STATUS)
VALUES ('BK002', 102, 'Maria Garcia', TO_DATE('2026-04-08', 'yyyy-mm-dd'), TO_DATE('2026-04-10', 'yyyy-mm-dd'), 2, 'Executive Suite', 600.00, 'CONFIRMED');

COMMIT;

PROMPT Data re-inserted and committed

PROMPT
PROMPT Verifying all data:

PROMPT ====== DS_1: HOTELS ======
SELECT * FROM TOURISM_ADMIN.HOTELS_DS1 ORDER BY HOTEL_ID;

PROMPT
PROMPT ====== DS_1: ROOM TYPES ======
SELECT * FROM TOURISM_ADMIN.ROOM_TYPES_DS1 ORDER BY ROOM_TYPE_ID;

PROMPT
PROMPT ====== DS_1: BOOKINGS ======
SELECT * FROM TOURISM_ADMIN.BOOKINGS_DS1 ORDER BY BOOKING_ID;

PROMPT
PROMPT ====== DS_2: FLIGHTS ======
SELECT * FROM TOURISM_ADMIN.FLIGHTS_DS2_CACHE ORDER BY FLIGHT_ID;

PROMPT
PROMPT ====== DS_3: CURRENCIES ======
SELECT * FROM TOURISM_ADMIN.CURRENCY_DS3 ORDER BY CURRENCY_CODE;

PROMPT
PROMPT ====== FEDERATION VIEWS ======
PROMPT
PROMPT V_DS1_HOTELS:
SELECT * FROM TOURISM_ADMIN.V_DS1_HOTELS;

PROMPT
PROMPT V_DS1_ROOMS:
SELECT * FROM TOURISM_ADMIN.V_DS1_ROOMS;

PROMPT
PROMPT V_DS1_BOOKINGS:
SELECT * FROM TOURISM_ADMIN.V_DS1_BOOKINGS;

PROMPT
PROMPT V_DS2_FLIGHTS:
SELECT * FROM TOURISM_ADMIN.V_DS2_FLIGHTS;

PROMPT
PROMPT V_DS3_CURRENCIES:
SELECT * FROM TOURISM_ADMIN.V_DS3_CURRENCIES;

PROMPT
PROMPT ====== FEDERATION SUMMARY ======
SELECT * FROM TOURISM_ADMIN.V_FEDERATION_SUMMARY;

EXIT;
